let express = require("express")
const { reg, login, editprofile, forgotpass, sendOtp, verifyOtp, auth } = require("../controllers/usercontroller")
const { getprod, upload, add, delprod, search, edit, editimg } = require("../controllers/prodcont")
const { addcart, getcart, inc, dec, delcart } = require("../controllers/cartcontroller")

let router = new express.Router()
router.post("/reg", reg)
router.post("/login", login)
router.get("/products", getprod)
router.post("/addprod", upload.single("pimg"), add)
router.post("/addcart",auth, addcart)
router.get("/getcart/:uid", getcart)
router.get("/inc/:cid", inc)
router.get("/dec/:cid", dec)
router.delete("/delcart/:cid", delcart)
router.delete("/delprod/:id", delprod)
router.get("/search/:sid?", search) // if u add ? means sid is optional and it is a query parameter
router.put("/edit", edit)
router.put("/editimg", upload.single("pimg"), editimg)
router.put("/editprofile",editprofile)
router.put("/forgotpass",forgotpass)
router.post('/sendotp', sendOtp)
router.post('/verifyotp', verifyOtp)
module.exports = router